# Generated by Django 2.2.4 on 2019-09-25 18:34

import FarmCorner.render
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authorize',
            fields=[
                ('A_id', models.AutoField(primary_key=True, serialize=False)),
                ('A_name', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(default='', max_length=50)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='buyproduct',
            fields=[
                ('B_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_id', models.IntegerField(default=0)),
                ('F_id', models.IntegerField(default=0)),
                ('F_name', models.CharField(default='', max_length=20)),
                ('T_name', models.CharField(default='', max_length=20)),
                ('P_name', models.CharField(default='', max_length=20)),
                ('Quantity', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
            ],
        ),
        migrations.CreateModel(
            name='eholder',
            fields=[
                ('H_id', models.AutoField(primary_key=True, serialize=False)),
                ('H_name', models.CharField(default='', max_length=20)),
                ('shop_name', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=70)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('District', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Anand', 'Anand'), ('Aravalli', 'Aravalli'), ('Amreli', 'Amreli'), ('Bharuch', 'Bharuch'), ('Botad', ' Botad'), ('Bhavnagar', 'Bhavnagar'), ('Banaskantha', 'Banaskantha'), ('Chhota Udaipur', 'Chhota Udaipur'), ('Dang', 'Dang'), ('Devbhoomi Dwarka', 'Devbhoomi Dwarka'), ('Dahod', 'Dahod'), ('Gandhinagar', 'Gandhinagar'), ('Gir Somnath', 'Gir Somnath'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Kachchh', 'Kachchh'), ('Kheda', 'Kheda'), ('Morbi', 'Morbi'), ('Mehsana', 'Mehsana'), ('Mahisagar', 'Mahisagar'), ('Mahisagar', 'Narmada'), ('Navsari', 'Navsari'), ('Panchmahal', 'Panchmahal'), ('Patan', 'Patan'), ('Porbandar', 'Porbandar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Sabarkantha', 'Sabarkantha'), ('Surendranagar', 'Surendranagar'), ('Tapi', 'Tapi'), ('Valsad', 'Valsad'), ('Vadodara', 'Vadodara')], default='', max_length=15)),
                ('Taluka', models.CharField(default='', max_length=15)),
                ('City', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Pincode', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=30)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farmerreg',
            fields=[
                ('F_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=20)),
                ('Address', models.CharField(default='', max_length=70)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('District', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Anand', 'Anand'), ('Aravalli', 'Aravalli'), ('Amreli', 'Amreli'), ('Bharuch', 'Bharuch'), ('Botad', ' Botad'), ('Bhavnagar', 'Bhavnagar'), ('Banaskantha', 'Banaskantha'), ('Chhota Udaipur', 'Chhota Udaipur'), ('Dang', 'Dang'), ('Devbhoomi Dwarka', 'Devbhoomi Dwarka'), ('Dahod', 'Dahod'), ('Gandhinagar', 'Gandhinagar'), ('Gir Somnath', 'Gir Somnath'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Kachchh', 'Kachchh'), ('Kheda', 'Kheda'), ('Morbi', 'Morbi'), ('Mehsana', 'Mehsana'), ('Mahisagar', 'Mahisagar'), ('Mahisagar', 'Narmada'), ('Navsari', 'Navsari'), ('Panchmahal', 'Panchmahal'), ('Patan', 'Patan'), ('Porbandar', 'Porbandar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Sabarkantha', 'Sabarkantha'), ('Surendranagar', 'Surendranagar'), ('Tapi', 'Tapi'), ('Valsad', 'Valsad'), ('Vadodara', 'Vadodara')], default='', max_length=15)),
                ('Taluka', models.CharField(default='', max_length=15)),
                ('City', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Area', models.CharField(default='', max_length=10)),
                ('Pincode', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=20)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='rentequipment',
            fields=[
                ('R_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_id', models.IntegerField(default=0)),
                ('H_id', models.IntegerField(default=0)),
                ('E_id', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=15)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Address', models.CharField(default='', max_length=70)),
                ('City', models.CharField(default='', max_length=15)),
                ('Pincode', models.IntegerField(default=0)),
                ('startdate', models.DateField(verbose_name=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
                ('enddate', models.DateField(verbose_name=datetime.datetime)),
                ('status', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
            ],
        ),
        migrations.CreateModel(
            name='traderreg',
            fields=[
                ('T_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=70)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('District', models.CharField(choices=[('Ahmedabad', 'Ahmedabad'), ('Anand', 'Anand'), ('Aravalli', 'Aravalli'), ('Amreli', 'Amreli'), ('Bharuch', 'Bharuch'), ('Botad', ' Botad'), ('Bhavnagar', 'Bhavnagar'), ('Banaskantha', 'Banaskantha'), ('Chhota Udaipur', 'Chhota Udaipur'), ('Dang', 'Dang'), ('Devbhoomi Dwarka', 'Devbhoomi Dwarka'), ('Dahod', 'Dahod'), ('Gandhinagar', 'Gandhinagar'), ('Gir Somnath', 'Gir Somnath'), ('Jamnagar', 'Jamnagar'), ('Junagadh', 'Junagadh'), ('Kachchh', 'Kachchh'), ('Kheda', 'Kheda'), ('Morbi', 'Morbi'), ('Mehsana', 'Mehsana'), ('Mahisagar', 'Mahisagar'), ('Mahisagar', 'Narmada'), ('Navsari', 'Navsari'), ('Panchmahal', 'Panchmahal'), ('Patan', 'Patan'), ('Porbandar', 'Porbandar'), ('Rajkot', 'Rajkot'), ('Surat', 'Surat'), ('Sabarkantha', 'Sabarkantha'), ('Surendranagar', 'Surendranagar'), ('Tapi', 'Tapi'), ('Valsad', 'Valsad'), ('Vadodara', 'Vadodara')], default='', max_length=15)),
                ('Taluka', models.CharField(default='', max_length=15)),
                ('City', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Pincode', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=30)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('Rb_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_id', models.IntegerField(default=0)),
                ('F_id', models.IntegerField(default=0)),
                ('H_id', models.IntegerField(default=0)),
                ('R_id', models.IntegerField(default=0)),
                ('P_id', models.IntegerField(default=0)),
                ('E_id', models.IntegerField(default=0)),
                ('F_name', models.CharField(default='', max_length=20)),
                ('T_name', models.CharField(default='', max_length=20)),
                ('Name', models.CharField(default='', max_length=20)),
                ('H_name', models.CharField(default='', max_length=20)),
                ('Total', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
            ],
        ),
        migrations.CreateModel(
            name='uploadequip',
            fields=[
                ('E_id', models.AutoField(primary_key=True, serialize=False)),
                ('H_id', models.IntegerField(default=0)),
                ('H_name', models.CharField(default='', max_length=40)),
                ('E_name', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=15)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('Category', models.CharField(choices=[('tractor', 'tractor'), ('tiller', 'tiller'), ('Harvesters', 'Harvesters'), ('Sowing and Planting Equipments', 'Sowing and Planting Equipments'), ('Pesticide applicators', 'Pesticide applicators'), ('landscaping Equipments', 'landscaping Equipments'), ('postharvest equipments', 'postharvest equipments')], default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('Image', models.ImageField(default='', upload_to='Image', validators=[FarmCorner.render.validate_file_size])),
                ('Rent_price', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='uploadprice',
            fields=[
                ('P_id', models.AutoField(primary_key=True, serialize=False)),
                ('T_id', models.IntegerField(default=0)),
                ('T_name', models.CharField(default='', max_length=20)),
                ('P_name', models.CharField(default='', max_length=20)),
                ('Price', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
            ],
        ),
        migrations.CreateModel(
            name='uproduct',
            fields=[
                ('S_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_id', models.IntegerField(default=0)),
                ('F_name', models.CharField(default='', max_length=20)),
                ('P_name', models.CharField(default='', max_length=20)),
                ('Mobileno', models.CharField(default='', max_length=13)),
                ('City', models.CharField(default='', max_length=15)),
                ('Image', models.ImageField(default='', upload_to='Image')),
                ('email', models.EmailField(default='', max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('mydate', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 0, 4, 15, 551218))),
            ],
        ),
    ]
