# Generated by Django 2.2.4 on 2019-11-05 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0004_auto_20191017_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadprice',
            name='Gradea',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='uploadprice',
            name='Gradeb',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='uploadprice',
            name='Gradec',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='uproduct',
            name='Grade',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='Category',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Tiller', 'Tiller'), ('Harvesters', 'Harvesters'), ('Sowing and Planting Equipments', 'Sowing and Planting Equipments'), ('Pesticide Applicators', 'Pesticide Applicators'), ('Landscaping Equipments', 'Landscaping Equipments'), ('postharvest Equipments', 'postharvest Equipments'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 21, 0, 0, 278125)),
        ),
    ]
