# Generated by Django 2.2.4 on 2019-11-07 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0005_auto_20191105_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadequip',
            name='hp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadequip',
            name='year',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='Gradea',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='Gradeb',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='Gradec',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 3, 40, 25, 793323)),
        ),
    ]
