# Generated by Django 2.2.4 on 2019-09-28 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0005_auto_20190927_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 99210)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='District',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 93194)),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='District',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 92693)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 98207)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 9, 29, 0, 10, 32, 98207)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='District',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 94698)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 99711)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 94196)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 94196)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 94196)),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 96202)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 29, 0, 10, 32, 97706)),
        ),
    ]
