# Generated by Django 2.2.4 on 2019-10-15 00:05

import FarmCorner.render
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0011_auto_20191001_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentequipment',
            name='Rating',
            field=models.FloatField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='authorize',
            name='A_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='F_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='P_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='Price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='T_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='H_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 793421)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='shop_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='F_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 792920)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='Name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='T_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 794450)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='F_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='H_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='T_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='Category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('tiller', 'Tiller'), ('Harvesters', 'Harvesters'), ('Sowing and Planting Equipments', 'Sowing and Planting Equipments'), ('Pesticide applicators', 'Pesticide Applicators'), ('landscaping Equipments', 'Landscaping Equipments'), ('postharvest equipments', 'postharvest Equipments'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='E_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='Rent_price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 793946)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 793946)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 793946)),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='P_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='Price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='T_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='F_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='Image',
            field=models.ImageField(default='', upload_to='Image', validators=[FarmCorner.render.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='P_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 5, 35, 41, 795452)),
        ),
    ]
