# Generated by Django 2.2.4 on 2019-11-14 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0011_auto_20191113_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 981275)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 981275)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 15, 4, 38, 28, 981275)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 981275)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='Category',
            field=models.CharField(choices=[('Tractor', 'Tractor'), ('Tillage', 'Tillage'), ('Harvesters', 'Harvesters'), ('Seeding and Plantation', 'Seeding and Plantation'), ('Crop Protection', 'Crop Protection'), ('Landscaping Equipments', 'Landscaping Equipments'), ('postharvest Equipments', 'postharvest Equipments'), ('Haulage', 'Haulage'), ('Others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 965653)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 4, 38, 28, 981275)),
        ),
    ]
