# Generated by Django 2.2.4 on 2019-11-28 22:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmCorner', '0019_auto_20191125_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='eholder',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmCorner.districts'),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='Taluka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmCorner.talukas'),
        ),
        migrations.AlterField(
            model_name='farmerreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='rentequipment',
            name='startdate',
            field=models.DateField(verbose_name=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='traderreg',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='enddate',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='uploadequip',
            name='startdate',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='uploadprice',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
        migrations.AlterField(
            model_name='uproduct',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 29, 4, 17, 53, 956783)),
        ),
    ]
